[
    {"id":"1","fruit_name":"Apple","details":"detail of apple" },
    {"id":"2","fruit_name":"Apricot"},
    {"id":"3","fruit_name":"Avocado"},
    {"id":"4","fruit_name":"Banana"},
    {"id":"5","fruit_name":"Bilberry"},
    {"id":"6","fruit_name":"Blackberry"},
    {"id":"7","fruit_name":"Blackcurrant"},
    {"id":"8","fruit_name":"Blueberry"},
    {"id":"9","fruit_name":"Boysenberry"},
    {"id":"10","fruit_name":"Cherry"},
    {"id":"11","fruit_name":"Cloudberry"},
    {"id":"12","fruit_name":"Coconut"},
    {"id":"13","fruit_name":"Cranberry"},
    {"id":"14","fruit_name":"Cucumber"},
    {"id":"15","fruit_name":"Dragonfruit"},
    {"id":"16","fruit_name":"Elderberry"},
    {"id":"17","fruit_name":"Goji berry"},
    {"id":"18","fruit_name":"Gooseberry"},
    {"id":"19","fruit_name":"Grape"},
    {"id":"20","fruit_name":"Guava"},
    {"id":"21","fruit_name":"Honeyberry"},
    {"id":"22","fruit_name":"Huckleberry"}
]